# Generated by Django 4.0.2 on 2022-02-12 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0002_remove_student_password2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hold', models.CharField(max_length=200)),
            ],
        ),
    ]
