# Generated by Django 4.0.2 on 2022-02-12 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0003_sess'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sess',
        ),
        migrations.AddField(
            model_name='student',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
