# Generated by Django 4.0.2 on 2022-02-16 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0009_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='discription',
            field=models.CharField(max_length=100000, null=True),
        ),
    ]
